#!/bin/bash
# Exit immediately if a command exits with a non-zero status
set -e

# --- CONFIGURATION ---
# The target python script to parse
SCRIPT_NAME="astroarch_bridge_dashboard.py"
# Directory where translation files are stored
LOCALE_DIR="locales"
# Universal template file generated by xgettext
POT_FILE="$LOCALE_DIR/base.pot"

# --- MANAGED LANGUAGES LIST ---
# Add or remove any ISO language code here to scale the project (e.g., "en" "es" "de")
LANGUAGES=("it" "fr" "es" "de")

echo "=== [1/3] Step A: Extracting text to POT template ==="
mkdir -p "$LOCALE_DIR"
xgettext --from-code=UTF-8 -d base -o "$POT_FILE" "$SCRIPT_NAME"
echo "-> Universal template updated: $POT_FILE"
echo ""

echo "=== [2/3] Step B: Syncing all languages ==="
# Loop through each language defined in the array to synchronize files
for LANG_CODE in "${LANGUAGES[@]}"; do
    echo "Processing [$LANG_CODE]..."
    LANG_MESSAGES_DIR="$LOCALE_DIR/$LANG_CODE/LC_MESSAGES"
    mkdir -p "$LANG_MESSAGES_DIR"

    # Target PO file path for the current language loop
    PO_FILE="$LANG_MESSAGES_DIR/base.po"

    if [ ! -f "$PO_FILE" ]; then
        # Initialize a brand new translation file if it does not exist yet
        msginit -i "$POT_FILE" -o "$PO_FILE" -l "$LANG_CODE" --no-translator
        echo "  └─> Created NEW translation file"
    else
        # Safely merge new strings into the existing PO file without losing old translations
        msgmerge -U "$PO_FILE" "$POT_FILE"
        echo "  └─> Updated existing file (merged new strings)"
    fi
done
echo "-> All language directories are synchronized."
echo ""

# --- INTERACTIVE MENU FOR EDITING & COMPILING ---
echo "=== [3/3] Step C & D: Management Menu ==="
echo "What would you like to do now?"
echo "1) Edit a translation file (.po)"
echo "2) Compile all translations to binary (.mo) and exit"
echo "3) Exit without compiling"
read -rp "Choice [1-3]: " MAIN_CHOICE

case "$MAIN_CHOICE" in
    1)
        echo ""
        echo "Select the language to translate/edit:"
        select LANG_CODE in "${LANGUAGES[@]}"; do
            if [ -n "$LANG_CODE" ]; then
                PO_FILE="$LOCALE_DIR/$LANG_CODE/LC_MESSAGES/base.po"
                MO_FILE="$LOCALE_DIR/$LANG_CODE/LC_MESSAGES/base.mo"

                # Check and launch the best available text or localization editor
                if command -v poedit >/dev/null 2>&1; then
                    poedit "$PO_FILE"
                elif [ -n "$DISPLAY" ] && command -v kwrite >/dev/null 2>&1; then
                    kwrite "$PO_FILE"
                elif command -v nano >/dev/null 2>&1; then
                    nano "$PO_FILE"
                else
                    vi "$PO_FILE"
                fi

                # Automatically compile this specific language immediately after closing the editor
                echo "Compiling $LANG_CODE..."
                msgfmt "$PO_FILE" -o "$MO_FILE"
                break
            else
                echo "Invalid selection."
            fi
        done
        ;;
    2)
        echo "Compiling all languages..."
        # Loop through the list to compile every available PO file into binary MO files
        for LANG_CODE in "${LANGUAGES[@]}"; do
            PO_FILE="$LOCALE_DIR/$LANG_CODE/LC_MESSAGES/base.po"
            MO_FILE="$LOCALE_DIR/$LANG_CODE/LC_MESSAGES/base.mo"
            if [ -f "$PO_FILE" ]; then
                msgfmt "$PO_FILE" -o "$MO_FILE"
                echo "  └─> [$LANG_CODE] compiled successfully."
            fi
        done
        ;;
    *)
        echo "Exiting."
        exit 0
        ;;
esac

echo "=== Done! ==="
